paths:
  data_folder: "./Data/sleeklady"
  formatted_folder: "./artifacts/sleeklady/formatted"
  filtered_folder: "./artifacts/sleeklady/filtered"
  dropped_folder: "./artifacts/sleeklady/dropped_columns"
  brands_folder: "./artifacts/sleeklady/brands"
  categories_folder: "./artifacts/sleeklady/categories"
  store_folder: "./artifacts/sleeklady/store"
  columns_created: "./artifacts/sleeklady/columns_created"
  product_description_folder: "./artifacts/sleeklady/product_description"
  product_code_folder: "./artifacts/sleeklady/product_codes"
  capitalized_folder: "./artifacts/sleeklady/capitalized"
  final_excel_folder: "./artifacts/sleeklady/final_excel"

files:
  input_excel: "ALKHEMY JAN 2025 DATA.xlsx"
  input_csv: "Sheet1.csv"
  filtered_csv: "alkhemy_brands_data.csv"
  dropped_csv: "alkhemy_brands_dropped_columns.csv"
  brands_csv: "alkhemy_brands_with_brands_column.csv"
  modified_csv: "modified_file.csv"
  store_mapping_json: "./src/sleeklady/configurations/store_name.json"
  modified_with_resolved_store_names_csv: "modified_with_resolved_store_names.csv"
  columns_added_csv: "columns_added.csv"
  product_description_json: "./src/sleeklady/configurations/product_description.json"
  updated_product_descriptions_csv: "updated_product_descriptions.csv"
  product_codes_json: "./src/sleeklady/configurations/product_codes.json"
  updated_product_codes_csv: "updated_product_codes.csv"
  input_product_codes_csv: "updated_product_codes.csv"

  output_capitalized_csv: "capitalized_data.csv"
  input_capitalized_csv: "capitalized_data.csv" 
  output_excel_filename: "final_output.xlsx"

filters:
  supplier_name: "ALKHEMY BRANDS"

columns_to_drop:
  - "YYYYMMDD"
  - "ProductCodes"
  - "SupplierNames"

brand_conditions:
  - ["MIKALLA", "Mikalla"]
  - ["H&B", "H&B"]

product_classification_patterns:
  Hair Treatment: "(treatment|treat|trt|moyonnaise)"
  Hair Shampoo: "(clen&cond shamp|clen|shampoo|shamp|charc dtx sham)"
  Hair Conditioner: "(conditioner|cond)"
  Hair Food: "(scalp soother|s/soother|h/food|anti dandruff creme|anti dandruff crm|crm|anti dandruff cream)"
  Hair Gel: "(gels|gel|curl activator)"
  Hair Spray: "spray"
  Body Lotion: "(lotion|b/ltn)"
  Body Scrub: "(scrub|b/scrub)"

patterns:
  store_name_pattern: "(SleekLady B\\d+)"

columns:
  rename:
    TotalSellingPrice: "Total Sales"
  account_name: "Sleeklady Cosmetics"
  group: "MT"
  sales_rep: "Leah"
  date: "JAN25"
  account_code: "SLE003"
