paths:
  data_folder: "./Data/sleeklady"
  formatted_folder: "./artifacts/sleeklady/formatted"
  filtered_folder: "./artifacts/sleeklady/filtered"
  dropped_folder: "./artifacts/sleeklady/dropped_columns"
  brands_folder: "./artifacts/sleeklady/brands"
  categories_folder: "./artifacts/sleeklady/categories"
  store_folder: "./artifacts/sleeklady/store"
  columns_created: "./artifacts/sleeklady/columns_created"
  product_description: "./artifacts/sleeklady/product_description"
  product_code: "./artifacts/sleeklady/product_code"
  capitalized_folder: "./artifacts/sleeklady/capitalized"
  final_excel_folder: "./artifacts/sleeklady/final_excel"

files:
  input_excel: "ALKHEMY BRANDS DEC 2024.xlsx"
  input_csv: "Sheet1.csv"
  filtered_csv: "alkhemy_brands_data.csv"

filters:
  supplier_name: "ALKHEMY BRANDS"