import pandas as pd
import json
import os

# Define paths
input_file = "artifacts/naivas/product_description/updated_product_descriptions.csv"
output_folder = "artifacts/naivas/product_code"
output_file = os.path.join(output_folder, "final_product_codes.csv")

# Ensure output directory exists
os.makedirs(output_folder, exist_ok=True)

# Product codes mapping
product_codes = {

    "FPADCCS": "MIKALLA ANTI-DANDRUFF SHAMPOO",
    "FPADHC150GM": "MIKALLA ANTI-DANDRUFF CREAM 150G",
    "FPADHC275GM": "MIKALLA ANTI-DANDRUFF CREAM 275G",
    "FPADHC75GM": "MIKALLA ANTI-DANDRUFF CREAM 75G",
    "FPALL155ML": "H&B ARGAN&LAVENDER LOTION 155ML",
    "FPALL280ML": "H&B ARGAN&LAVENDER LOTION 280ML",
    "FPALL420ML": "H&B ARGAN&LAVENDER LOTION 420ML",
    "FPBBL155ML": "H&B BERRY BLOSSOM LOTION 155ML",
    "FPBBL280ML": "H&B BERRY BLOSSOM LOTION 280ML",
    "FPBBL420ML": "H&B BERRY BLOSSOM LOTION 420ML",
    "FPBF300GM": "H&B BERRY FUSION BODY SCRUB 300GM-DEACTIVATED",
    "FPBF700GM": "H&B BERRY FUSION BODY SCRUB 700GM-DEACTIVATED",
    "FPBFS300GM": "H&B BERRY FUSION SCRUB 300G",
    "FPBFS700GM": "H&B BERRY FUSION SCRUB 700G",
    "FPBS120ML": "MIKALLA 5IN1 BRAID SPRAY 120ML",
    "FPBS250ML": "MIKALLA 5IN1 BRAID SPRAY 250ML",
    "FPBS65ML": "MIKALLA 5IN1 BRAID SPRAY 65ML",
    "FPCAG150GM": "MIKALLA CURL ACTIVATOR GEL 150G",
    "FPCAG250GM": "MIKALLA CURL ACTIVATOR GEL 250G",
    "FPCAG450GM": "MIKALLA CURL ACTIVATOR GEL 450G",
    "FPCBL155ML": "H&B COCOA BUTTER LOTION 155ML",
    "FPCBL280ML": "H&B COCOA BUTTER LOTION 280ML",
    "FPCBL420ML": "H&B COCOA BUTTER LOTION 420ML",
    "FPCCS1000ML": "MIKALLA SHAMPOO 1LITRE",
    "FPCCS450ML": "MIKALLA SHAMPOO 450ML",
    "FPCCS5000ML": "MIKALLA SHAMPOO 5LITRE",
    "FPCCS65ML": "MIKALLA SHAMPOO 65ML (SAMPLE)",
    "FPCDCCS": "MIKALLA CHARCOAL DETOX SHAMPOO",
    "FPCVS300GM": "H&B COFFEE VANILLA SCRUB 300G",
    "FPCVS700GM": "H&B COFFEE VANILLA SCRUB 700G",
    "FPDCK240ML": "MIKALLA DETANGLING CONDITIONER KIDS 240ML",
    "FPECG250G": "MIKALLA EDGE CONTROL GEL KIDS 250G",
    "FPEML155ML": "H&B EPIC MAN LOTION 155ML",
    "FPEML280ML": "H&B EPIC MAN LOTION 280ML",
    "FPEML420ML": "H&B EPIC MAN LOTION 420ML",
    "FPHBC1000ML": "MIKALLA HONEY & BUTTER CONDITIONER 1LITRE",
    "FPHBC450ML": "MIKALLA HONEY & BUTTER CONDITIONER 450ML",
    "FPHBC5000ML": "MIKALLA HONEY & BUTTER CONDITIONER 5LITRE",
    "FPHBC65ML": "MIKALLA HONEY & BUTTER CONDITIONER 65ML (SAMPLE)",
    "FPHFSS150GM": "MIKALLA SCALP SOOTHER HAIRFOOD 150G",
    "FPHFSS250GM": "MIKALLA SCALP SOOTHER HAIRFOOD 250G",
    "FPHFSS400GM": "MIKALLA SCALP SOOTHER HAIRFOOD 400G",
    "FPHFSS75GM": "MIKALLA SCALP SOOTHER HAIRFOOD 75G",
    "FPHMT1100GM": "MIKALLA MAYONNAISE TREATMENT 1100G",
    "FPHMT261GM": "MIKALLA MAYONNAISE TREATMENT 261G",
    "FPHMT407GM": "MIKALLA MAYONNAISE TREATMENT 407G",
    "FPHMT700G": "MIKALLA MAYONNAISE TREATMENT 700G",
    "FPLT1000ML": "MIKALLA LEAVE-IN TREATMENT 1LITRE",
    "FPLT100ML": "MIKALLA LEAVE-IN TREATMENT 100ML",
    "FPLT250ML": "MIKALLA LEAVE-IN TREATMENT 250ML",
    "FPLT450ML": "MIKALLA LEAVE-IN TREATMENT 450ML",
    "FPLT65ML": "MIKALLA LEAVE-IN TREATMENT 65ML (SAMPLE)",
    "FPLTK240ML": "MIKALLA LEAVE-IN TREATMENT KIDS 240ML",
    "FPMTK250G": "MIKALLA DEEP MOISTURE TREATMENT KIDS 250G",
    "FPNHF150GM": "MIKALLA NOURISHING HAIR FOOD 150G",
    "FPNHF250GM": "MIKALLA NOURISHING HAIR FOOD 250G",
    "FPNHF400GM": "MIKALLA NOURISHING HAIR FOOD 400G",
    "FPNHF75GM": "MIKALLA NOURISHING HAIR FOOD 75G",
    "FPOEL155ML": "H&B OATMEAL EXTRACT LOTION 155ML",
    "FPOEL280ML": "H&B OATMEAL EXTRACT LOTION 280ML",
    "FPOEL420ML": "H&B OATMEAL EXTRACT LOTION 420ML",
    "FPQT1000GM": "MIKALLA QUADRA OIL TREATMENT 1KG",
    "FPQT150GM": "MIKALLA QUADRA OIL TREATMENT 150G",
    "FPQT250GM": "MIKALLA QUADRA OIL TREATMENT 250G",
    "FPQT400GM": "MIKALLA QUADRA OIL TREATMENT 400G",
    "FPQT700GM": "MIKALLA QUADRA OIL TREATMENT 700G",
    "FPSBL155ML": "H&B SHEA BUTTER LOTION 155ML",
    "FPSBL280ML": "H&B SHEA BUTTER LOTION 280ML",
    "FPSBL420ML": "H&B SHEA BUTTER LOTION 420ML",
    "FPSFCCS": "MIKALLA SULPHATE FREE SHAMPOO",
    "FPSG150GM": "MIKALLA STYLING GEL 150G",
    "FPSG250GM": "MIKALLA STYLING GEL 250G",
    "FPSG450GM": "MIKALLA STYLING GEL 450G",
    "FPTFKS250ML": "MIKALLA TEAR FREE KIDS SHAMPOO 250ML",
    "FPVSCCS": "MIKALLA VOLUME + STRENGTH SHAMPOO"

  }
  
# Read input file
df = pd.read_csv(input_file)

# Create a reverse lookup dictionary
description_to_code = {v: k for k, v in product_codes.items()}

# Assign product codes
df["product_code"] = df["DESCRIPTION"].map(description_to_code)

# Save output
df.to_csv(output_file, index=False)

print(f"File saved: {output_file}")
